name: tompa

description: TOMPA - mobile accounting app starter project.

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3
  path: ^1.9.0
  intl: ^0.19.0
  pdf: ^3.11.0
  printing: ^5.13.0

# Planned later:
# excel: ^4.0.3
# file_picker: ^8.0.0
# image_picker: ^1.1.2
# supabase_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
